### ISSUE TITLE
read  nodecharts.config.js error

### ISSUE THREAD

**Issue by Code1912** [JerrZhang/node-charts#1]
文件读取位置错误啊  
 tryReadExternalConfig() {
        //
        let appRoot = '../../nodechart.config.js'

 mac 系统，
我工目录是 src/app.js
这样读取到的 approot会是/users/xx/nodecharts.js 

用 path.resolve 会不会好些？

**Comment by JerrZhang** [comment]
谢谢提醒，代码已更新，同时也增加显示方法，可定制configpath路径
可使用实例方法setExternalConfPath（configPath）显示指定外部配置文件路径

**Comment by Code1912** [comment]
还是有问题  ，你构造函数已经初始化了 ，然后再调用 setExternalConfPath 方法，不管用啊
